"""Add chat models

Revision ID: e1178e08305d
Revises: b6cf3908b7bc
Create Date: 2024-12-01 18:37:29.335180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1178e08305d'
down_revision: Union[str, None] = 'b6cf3908b7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.drop_index('ix_delivery_methods_id', table_name='delivery_methods')
    op.drop_table('delivery_methods')
    op.drop_index('ix_carts_id', table_name='carts')
    op.drop_table('carts')
    op.drop_index('ix_offers_id', table_name='offers')
    op.drop_table('offers')
    op.drop_index('ix_cart_items_id', table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_constraint(None, 'buyers', type_='foreignkey')
    op.create_foreign_key(None, 'buyers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('buyers', 'balance')
    op.drop_constraint(None, 'farmers', type_='foreignkey')
    op.create_foreign_key(None, 'farmers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('messages', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.alter_column('messages', 'timestamp',
               existing_type=sa.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_column('messages', 'receiver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('receiver_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    op.alter_column('messages', 'timestamp',
               existing_type=sa.TIMESTAMP(),
               nullable=True)
    op.drop_column('messages', 'conversation_id')
    op.drop_constraint(None, 'farmers', type_='foreignkey')
    op.create_foreign_key(None, 'farmers', 'users', ['user_id'], ['id'])
    op.add_column('buyers', sa.Column('balance', sa.FLOAT(), nullable=True))
    op.drop_constraint(None, 'buyers', type_='foreignkey')
    op.create_foreign_key(None, 'buyers', 'users', ['user_id'], ['id'])
    op.create_table('cart_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cart_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cart_items_id', 'cart_items', ['id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('buyer_id', sa.INTEGER(), nullable=True),
    sa.Column('proposed_price', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offers_id', 'offers', ['id'], unique=False)
    op.create_table('carts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('buyer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id')
    )
    op.create_index('ix_carts_id', 'carts', ['id'], unique=False)
    op.create_table('delivery_methods',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_delivery_methods_id', 'delivery_methods', ['id'], unique=False)
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
